kind: pipeline
type: docker
name: test

steps:
- name: install
  image: danlynn/ember-cli:3.28.5-node_16.13
  commands:
  - npm ci

- name: lint:js
  image: danlynn/ember-cli:3.28.5-node_16.13
  commands:
  - npm run lint:js
  depends_on:
  - install

- name: lint:hbs
  image: danlynn/ember-cli:3.28.5-node_16.13
  commands:
  - npm run lint:hbs
  depends_on:
  - install

- name: lint:dependencies
  image: danlynn/ember-cli:3.28.5-node_16.13
  failure: ignore
  commands:
  - ember dependency-lint
  depends_on:
  - install

- name: test
  image: danlynn/ember-cli:3.28.5-node_16.13
  failure: ignore
  commands:
  - npm run test:ember
  depends_on:
  - install

---

kind: pipeline
type: docker
name: build-dry-run

steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
    purge: true

trigger:
  event:
    - pull_request

---

kind: pipeline
type: docker
name: push-latest-build

steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request

---

kind: pipeline
type: docker
name: release

steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true

- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token

trigger:
  event:
    - tag

