kind: pipeline
type: docker
name: test

steps:
- name: install
  image: danlynn/ember-cli:3.28.5-node_16.13
  commands:
  - npm ci

- name: lint:js
  image: danlynn/ember-cli:3.28.5-node_16.13
  commands:
  - npm run lint:js
  depends_on:
  - install

- name: lint:hbs
  image: danlynn/ember-cli:3.28.5-node_16.13
  commands:
  - npm run lint:hbs
  depends_on:
  - install

- name: lint:dependencies
  image: danlynn/ember-cli:3.28.5-node_16.13
  failure: ignore
  commands:
  - ember dependency-lint
  depends_on:
  - install

- name: test
  image: danlynn/ember-cli:3.28.5-node_16.13
  failure: ignore
  commands:
  - npm run test:ember
  depends_on:
  - install

trigger:
  event:
    - pull_request

---

kind: pipeline
type: docker
name: compatibility
steps:
- name: ember-compatibility
  image: danlynn/ember-cli:3.28.5-node_16.13
  failure: ignore
  commands:
  - npm ci
  - npm run test:ember-compatibility

trigger:
  event:
    - pull_request

---

kind: pipeline
type: docker
name: release

steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token

trigger:
  event:
    - tag

---

kind: secret
name: npm_access_token
data: GQiUf9yit0Hpru5iKreNlLCeIzBxbHJIGWISPFcrI1NXPqZ+piMAFc3HgulhV960kyfVWwtwaSbx3qiINeT/KxGq7oQ=

